syncstorage/storage/__init__.py, syncstorage/storage/memcached.py, syncstorage/storage/sql/__init__.py, syncstorage/storage/sql/queries_generic.py, syncstorage/tests/functional/test_storage.py, syncstorage/views/validators.py
This was removed in the sync1.1 -> sync1.5 transition because clients
weren't using it, but we have new clients and they want to use it.
https://bugzilla.mozilla.org/show_bug.cgi?id=1212189
=> Bug 1212189 - restore the "sort=oldest" option to the API.

syncstorage/views/authentication.py
This change adds `fxa_uid` and `device_id` from the token to metrics log lines
=> add fxa uid and device_id to metrics

Dockerfile, README.md, circle.yml, docker-entrypoint.sh, example.ini
Changes: 
- add Dockerfile, based off of python:2.7-alpine to build a fairly small docker image
- add example.ini so docker container runs out of the box
- add shellscript as an `ENTRYPOINT` so container can be used like an executable
- add circle.yml for automated docker image building
This dockerizes server-syncstorage. Following closely with the precedents used by other [Dockerflow](https://github.com/mozilla-services/Dockerflow) like projects.  
@rfk r?
@Micheletto fyi
BTW: Here's what the [circleci output](https://circleci.com/gh/mostlygeek/server-syncstorage/20) will look like when this is merged and enabled. 
I did this so I could use the python functional tests to test that the [golang storage server](https://github.com/mostlygeek/go-syncstorage) passes the same functional tests. …
=> Add Dockerfile, circle.yml and ENTRYPOINT script

Dockerfile, docker-entrypoint.sh
Added `ca-certificates` to the docker build requirements. Now `test_functional` will work against https endpoints. It failed before because openssl and the ca-certificates were not installed. 
@rfk r?
=> fix functional tests failing against https endpoints

syncstorage/storage/sql/queries_generic.py, syncstorage/storage/sql/queries_mysql.py, syncstorage/storage/sql/queries_postgres.py, syncstorage/storage/sql/queries_sqlite.py, syncstorage/tests/functional/test_old_storage.py, syncstorage/tests/functional/test_storage.py, syncstorage/tests/test_scripts.py, syncstorage/tests/tests.ini, syncstorage/tweens.py, syncstorage/views/__init__.py, syncstorage/views/util.py, syncstorage/views/validators.py
@rtilder some tweaks to your db queries:
* Move queries with mysql-specific `ON DUPLICATE KEY` logic into `queries_mysql.py`
* Fix syntax error in sqlite `APPLY_BATCH` query due to mis-embedded double quotes
* Try to make some postgres-specific purge queries
* Remove `APPEND_ITEMS_TO_BATCH` which doesn't seem to be used
It doesn't get all the tests passing, but they're passing more than they were for non-mysql backends. @rtilder r?
=> Tweaks to get tests passing on batch uploads PR

syncstorage/storage/memcached.py, syncstorage/storage/sql/__init__.py, syncstorage/storage/sql/dbconnect.py, syncstorage/storage/sql/queries_generic.py, syncstorage/storage/sql/queries_mysql.py, syncstorage/storage/sql/queries_sqlite.py, syncstorage/tests/functional/test_storage.py, syncstorage/views/__init__.py
This fixes the handling of TTL updates in a batch upload, allowing us to unskip the final two testcases for the batch upload work.  See https://bugzilla.mozilla.org/show_bug.cgi?id=1311903.
@Natim r?
It got a little thorny sorry, since it uncovered a bug in the way that the memcache layer was handling TTLs.  It may be easiest to review one commit at a time, and I'll leave some comments below.
The guts of the change is in the third commit, which updates the DB queries to provide proper partial-update semantics:
* If the batch upload did not specify a value of a field, keep any existing value
* Otherwise, use the new value from the batch upload
=> Batch upload ttl fixes

syncstorage/tests/functional/test_storage.py, syncstorage/tests/tests-memcached-cacheonly.ini, syncstorage/tests/tests-memcached-writethrough.ini, syncstorage/tests/tests-no-batch.ini, syncstorage/tests/tests-paginated.ini, syncstorage/tests/tests.ini, syncstorage/views/__init__.py, syncstorage/views/validators.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1304627
This will let us roll out the new feature slowly, by only enabling it on nodes with the following config:
```
[storage]
batch_upload_enabled = true
```
It will be off by default.  Once we're happy that it's properly deployed in production, we can remove this and have it on all the time.
@Natim r?
=> Add a feature-flag for the batch upload feature.

syncstorage/bso.py, syncstorage/tests/functional/test_storage.py, syncstorage/views/__init__.py
In the non-batch case, we ignore individual invalid items and continue with processing the valid ones.  Since we want the semantics of batch uploads to be as close to non-batch as possible, we should apply the same rules there.
For a fun bonus, this uncovered an edge-case where we'd incorrectly accept a BSO id with a trailing newline, because regexes.
=> Make batch and non-batch posts have same semantics for invalid items.

syncstorage/storage/sql/queries_mysql.py
The ttls in that table are offests, and the batch ids are timestamps.  It makes more sense to order by batch id so that we're pruning an entire left subtree of the primary key.
@Natim r?
=> Don't try to purge batch_upload_items in ttl order.

syncstorage/storage/memcached.py, syncstorage/tests/functional/support.py, syncstorage/tests/functional/test_storage.py
The tests pass without any changes to the code, but it's nice
to have them explicit, especially since the batchid provides
a layer of indirection when writing to a collection.
@Natim r?
=> Add tests to ensure users can't write to each other's batches.

syncstorage/storage/__init__.py, syncstorage/storage/memcached.py, syncstorage/storage/sql/__init__.py, syncstorage/storage/sql/queries_generic.py, syncstorage/tests/functional/test_storage.py, syncstorage/views/__init__.py, syncstorage/views/validators.py
This was removed in sync 1.5 because clients weren't using it, but we've found a use-case for it now and there's basically no cost to bringing it back.  See https://bugzilla.mozilla.org/show_bug.cgi?id=1314171 for details.
@Natim r?  And don't worry, soon I'll go back to not having time for significant syncstorage work :-)
=> Bug 1314171 - Reintroduce the 'older' query parameter.

syncstorage/storage/sql/queries_generic.py, syncstorage/tests/functional/support.py, syncstorage/tests/test_memcachedsql.py
This issue was causing test failures when updating https://github.com/mozilla-services/syncserver to the latest tag.  Since it's only tests and lint, merging r=myself to fix the tests.
=> Skip user-switching functional tests when running them live.

circle.yml, syncstorage/tests/functional/test_storage.py
Ref: [Bug 1332552](https://bugzilla.mozilla.org/show_bug.cgi?id=1332552). iOS clients send a ttl:null for BSOs in the JSON. This
is meant to be interpreted as never expire. The gosync server doesn't
behave correctly with ttl=null. Add a test to prevent regressions.
@rfk r? please
=> Add a functional test for expected behaviour when ttl=null

syncstorage/scripts/__init__.py, syncstorage/scripts/mcclear.py, syncstorage/scripts/mcread.py, syncstorage/scripts/purgettl.py, syncstorage/storage/__init__.py, syncstorage/storage/sql/__init__.py, syncstorage/storage/sql/dbconnect.py, syncstorage/views/__init__.py, syncstorage/views/authentication.py, syncstorage/views/decorators.py, syncstorage/views/validators.py
Using MozLog the logger name provides some general context about the
source of the log event.
These changes will keep the logger names as before, except for the following
cases:
- ``syncstorage.scripts.prunettl`` →  ``syncstorage.scripts.purgettl``
- ``syncstorage.storage.sql`` →  ``syncstorage.storage.sql.dbconnect``
- ``syncstorage`` →  ``syncstorage.views``
- ``syncstorage`` →  ``syncstorage.views.authentication``
- ``syncstorage`` →  ``syncstorage.views.decorators``
See also:
* MozLog v2 in Sync https://bugzilla.mozilla.org/show_bug.cgi?id=1340674
* Related mozilla-services/mozservices#38
@rfk r?
=> Use module name as logger names

syncstorage/tests/functional/test_storage.py, syncstorage/views/validators.py
If we silently accept them, we'll do the wrong thing from what the client expects.
=> Reject in-flight batches when batch uploads are disabled.

syncstorage/storage/sql/__init__.py, syncstorage/storage/sql/dbconnect.py, syncstorage/storage/sql/queries_generic.py, syncstorage/storage/sql/queries_mysql.py, syncstorage/storage/sql/queries_sqlite.py, syncstorage/tests/functional/test_storage.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1345742
This adds an explicit "userid" column to the batch-upload-items table, so that we don't risk intermingling data uploaded by different users. @Natim r?
=> Bug 1345742 - don't intermingle batch uploads from multiple users.

syncstorage/storage/sql/__init__.py, syncstorage/storage/sql/queries_generic.py, syncstorage/storage/sql/queries_mysql.py, syncstorage/storage/sql/queries_postgres.py, syncstorage/storage/sql/queries_sqlite.py
We found that this can prevent MySQL from using an index in some circumstances, so instead let's pass in a timestamp from the application.
=> Bug 1388963 - Remove use of UNIX_TIMESTAMP() in queries.

syncstorage/tests/functional/test_storage.py, syncstorage/views/validators.py
This includes the tests from #71 and a code fix to make them pass.
=> Empty request body should be valid applicatiln/newlines input

syncstorage/tests/functional/test_old_storage.py, syncstorage/tests/functional/test_storage.py, syncstorage/tests/tests-memcached-cacheonly.ini, syncstorage/tests/tests-memcached-writethrough.ini, syncstorage/views/__init__.py, syncstorage/views/util.py, syncstorage/views/validators.py
Fixes #73, adds explicit functional tests to assert https://bugzilla.mozilla.org/show_bug.cgi?id=1401707, and includes "max_request_bytes" in the configuration report even when batches are enabled.
@mhammond r?  The changes here are mostly to test cases so if you could check whether they make sense from your perspective that'd be awesome.
=> Ensure all size limits are inclusive, and are internally consistent.

syncstorage/tests/functional/test_storage.py, syncstorage/views/util.py
This test was wildly overshooting the nginx limit on request body size when run against servers in stage.  I've adjusted it to be a little more conservative about how much data it sends, while still triggering the behaviour under test (which is the max BSO payload bytes, not max request bytes).
@Micheletto r?
=> Avoid triggering a 413 with large payload tests in prod.

.circleci/config.yml
The merge of #81 failed on master with the following:
```
#!/bin/bash -eo pipefail
set -x
curl -L -o /tmp/docker-$DOCKER_VERSION.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_VERSION.tgz
[[ `sha256sum /tmp/docker-17.12.1-ce.tgz  | cut -d' ' -f1` = 1270dce1bd7e1838d62ae21d2505d87f16efc1d9074645571daaefdfd0c14054 ]]
tar -xz -C /tmp -f /tmp/docker-$DOCKER_VERSION.tgz
mv /tmp/docker/* /usr/bin
+ curl -L -o /tmp/docker-.tgz https://download.docker.com/linux/static/stable/x86_64/docker-.tgz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   566  100   566    0     0   3590      0 --:--:-- --:--:-- --:--:--  3605
++ sha256sum /tmp/docker-17.12.1-ce.tgz
++ cut '-d ' -f1
sha256sum: …
```
=> fix(docker): Use $DOCKER_VERSION when checking checksum.

requirements.txt
This resolves the dependency warning for older versions of gunicorn, per https://github.com/mozilla-services/server-syncstorage/network/dependencies
I don't have any reason to believe there's an actual security issue here, but updating for completeness.
=> Update gunicorn dependency.

.travis.yml, CONTRIBUTORS.txt, Makefile, requirements.txt, setup.py
Travis CI is a great tool for having your package tested.
This pull requests:
* Drops support for Python 2.6 (seems to be out-of-scope with deps not even running on this old Python; as per [this comment](https://github.com/mozilla-services/tokenserver/issues/102#issuecomment-281698235) production runs Python 2.7)
* Switches pyscopg2 to psycobg2-binary, which is a prepared wheel that will cut down installation time
* Will let the makefile create a virtualenv with the systems Python. This gets important if you want to run multiple Python versions.
* Updates the URL of the PyPI index to the one used by pypi.org. The old one does not receive updates.
* Fixes building umemcache (was broken once the switch to system python was made)
* Switches from Distribute to setuptools because nowadays the …
=> Travis improvements

requirements.txt, setup.py
`umemcache` is an optional (extra) dependency of `mozsvc`.
`umemcache` is never used directly in this module.
Since `umemcache` is used with the version of `mozsvc.storage.memcached` installed the installation style for `mozsvc` has been changed to include the extra `memcache` - which will currently install `umemcache`.
If `mozsvc` changes its dependencies for _memcache_ these changes can be picked up much easier with this style.
My main motivation behind this is that porting this library to Python 3 gets easier without `umemcache` as a direct dependency because it only supports Python 2.
=> Change installation of umemcache

syncstorage/scripts/mcclear.py, syncstorage/scripts/mcread.py, syncstorage/storage/__init__.py, syncstorage/storage/memcached.py, syncstorage/storage/sql/__init__.py, syncstorage/tests/test_memcachedsql.py, syncstorage/tests/test_scripts.py, syncstorage/tests/test_sql.py, syncstorage/tests/test_storage.py, syncstorage/views/__init__.py, syncstorage/views/authentication.py, syncstorage/views/decorators.py, syncstorage/views/util.py
This passes the full `request.user` object through to backend storage implementations, rather than just the numeric userid.  With this change in place, a future backend could choose to grab the `fxa_uid` and `fxa_kid` keys out of `request.user` and use those for indexing into storage, rather than using the numeric id allocated by tokenserver.
It's a big change, but it's largely mechanical, and AFAIK it should be entirely contained to this repo.  The only weird bit was the handling of expired tokens, which took me a few attempts to get figured out, but I think has successfully maintained its simplicity and safety.
@bbangert thoughts? (and if it seems like a reasonable approach, r?)
Connects to https://github.com/mozilla-services/tokenserver/issues/121
=> feat(backend): Pass full user object to backend storage implementations.

syncstorage/tests/test_wsgiapp.py, syncstorage/views/authentication.py
This is a sketch of what might need to change in the storage code to support https://github.com/mozilla-services/tokenserver/issues/121, receiving the raw FxA uid and key-id as part of the tokenserver token.  There would need to be some additional figuring-out of how to pass these through to the storage backend, which currently expects to receive the numeric tokenserver userid as first argument.  Maybe we change it to pass in `request.user` instead of the raw id?
Connects to https://github.com/mozilla-services/tokenserver/issues/121; Depends on  #93.
/cc @bbangert @philbooth @pjenvey
=> Accept FxA user-id and key-id details in Hawk token.

syncstorage/storage/spanner.py, syncstorage/storage/sql/queries_spanner.py
- match the related SELECT query's default ordering of modified DESC
- interleave it into user_collections (it shares the same keys),
keeping the index data local to the parent's "split"
Closes #107
=> fix: force usage of BsoLastModified index

.circleci/config.yml
this can happen w/ circleci's older fallback git+ssh. prefer their
recommended docker:stable-git image
=> chore: fix circleci "object not found" on tag builds

syncstorage/tests/functional/test_old_storage.py, syncstorage/tests/functional/test_storage.py, syncstorage/tests/test_memcachedsql.py, syncstorage/tests/test_sql.py, syncstorage/tests/test_storage.py, syncstorage/tests/test_wsgiapp.py, syncstorage/tests/tests-memcached-cacheonly.ini, syncstorage/tests/tests-memcached-writethrough.ini
=> feat: Add delayed retry on 500/503 responses.

README.md
Closes [123](https://github.com/mozilla-services/server-syncstorage/issues/123)
=> docs: fix links to point to moved content

syncstorage/tests/functional/test_storage.py
Covers the behaviour mis-match behind https://github.com/mozilla-services/syncstorage-rs/pull/364 and  https://github.com/mozilla-services/syncstorage-rs/issues/376.
=> Add tests for the optional "collection" field on BSOs.

syncstorage/tests/test_wsgiapp.py
I wanted to test something about the behaviour of #136, so figured I may as well do it as an actual testcase. @jrconlin r?
=> Add an HTTP-level test that migration produces a 503.

syncstorage/storage/__init__.py, syncstorage/storage/memcached.py, syncstorage/storage/sql/__init__.py, syncstorage/storage/sql/dbconnect.py, syncstorage/storage/sql/queries_generic.py, syncstorage/tests/functional/support.py, syncstorage/tests/test_sql.py, syncstorage/tests/test_wsgiapp.py, syncstorage/tests/tests-hostname.ini, syncstorage/views/__init__.py, syncstorage/views/decorators.py
This branch adds support to look in a `migration` table for a user's
`fxa_uid` record. If it is found, the server will return a 5xx error to
the client preventing sync operations.
NOTE: IT IS IMPORTANT THAT THE SERVER NOT RETURN A 2xx RESULT TO ANY
CLIENT IN MIGRATION STATUS UNLESS THE `meta`/`global` BSO IS RESET.
The `migration` table is created by the `user_migration` script, which
is part of `syncstorage-rs`.
=> feat: Add table to cross check user migration status

syncstorage/tests/functional/test_storage.py, syncstorage/tests/test_wsgiapp.py, syncstorage/views/authentication.py
As of mozilla-services/tokenserver#143, the Tokenserver includes the full FxA key-ID into field `fxa_kid` for the Hawk auth token, with an example value being the following:
```
1596115912183-FSK_yn0nhZYlC9CrDYZ6xg
```
...whereas it previously was just the hex-encoded client-state value, which would have been:
```
1522bfca7d278596250bd0ab0d867ac6
```
The actual issue is here, that the storage-server tries to validate the value space for `fxa_kid` after validating the token, but does not account for the value-space of url-safe Base64.
=> Fix Hawk token content validation for new fxa_kid

.dockerignore, requirements.txt
While testing locally, I noticed that the docker image is getting relatively big, due to the fact that everything from the local workspace gets copied into the image:
```
Sending build context to Docker daemon  119.2MB
Step 1/10 : FROM python:2.7-alpine
...
```
So I created a simple `.dockerignore` file to exclude everything that's not needed inside, resulting in:
```
Sending build context to Docker daemon  349.2kB
Step 1/10 : FROM python:2.7-alpine
...
```
Although this does not apply much to the official images built by CI, it may still provide a more official-like experience when developing and testing locally:
```
server-syncstorage              latest              9217ced25ec4        35 minutes ago      211MB
server-syncstorage              1.8.0-local         d1871e1290f5        10 …
```
=> Add .dockerignore to reduce docker image size

.dockerignore
With merging #151 , the CircleCI build became broken due to missing tests inside the docker image.
=> Include tests into docker image to make CircleCI build happy

requirements.txt
Noticed when I went to open a separate PR that we're failing safety checks so builds are failing. Upgraded related deps.
Ran `make safeycheck` locally - it passes. Now let's wait for CI...
Closes [#157](https://github.com/mozilla-services/server-syncstorage/issues/157).
=> task: upgrade urllib3 to fix safetycheck and dependent lib requests

Makefile, setup.py
Previously, this repo had two sets of requirements: one in `requirements.txt`
that we'd use when building the project via `make`, and one in `setup.py`
that we'd use if installing it as a depenency via pip.
This has been causing problems for self-hosters, so let's have `setup.py`
just read the list of requirements out of `requirements.txt` and avoid
needing to keep two lists of requirements in sync.
(The logic here is copied directly from the tokenserver `setup.py`,
and I've taken the opportunity to copy over some other `Makefile` tweaks
while I'm here).
=> Use `requirements.txt` as source of truth for requirements in setup.py

.circleci/config.yml, Makefile
Marking as a draft until confirming this fixes CI
=> chore: pin safety to its last version supporting python2
