mozilla-services/server-syncstorage

setup.py

Prep version 1.5.14

---

loadtest/stress.py
syncstorage/storage/sql/__init__.py
syncstorage/tests/functional/test_old_storage.py
syncstorage/tests/functional/test_storage.py
syncstorage/tests/tests.ini
syncstorage/views/validators.py

https://bugzilla.mozilla.org/show_bug.cgi?id=1250747

Bug 1250747 - make per-batch item limit configurable

---

syncstorage/storage/sql/queries_mysql.py

@l-hedgehog does this look OK to you?

Use correct name for PURGE_SOME_EXPIRED_ITEMS in mysql specific queries.

---

syncstorage/storage/sql/__init__.py
syncstorage/storage/sql/dbconnect.py

This is not supported in newer versions of MySQL.  @rtilder r?

Dont try to set a default on a MySQL TEXT column.

---

syncstorage/bso.py
syncstorage/tests/test_wsgiapp.py
syncstorage/views/validators.py

In service of https://bugzilla.mozilla.org/show_bug.cgi?id=1300451

Bug 1300451 - log data about invalid BSOs.

---

syncstorage/storage/sql/__init__.py

@rtilder my apologies if this clobbers a fix you already had in the works, but I couldn't find your WIP and :bobm was asking after this again last standup.  Context:
https://bugzilla.mozilla.org/show_bug.cgi?id=1273102#c18
@rtilder or @Natim r?

Ensure proper distribution when sharding by batchid.

---

syncstorage/tests/functional/test_storage.py
syncstorage/views/__init__.py
syncstorage/views/decorators.py

https://bugzilla.mozilla.org/show_bug.cgi?id=1062120

Bug 1062120 - Fail the whole POST request if we get a DB error

---

syncstorage/storage/memcached.py

Cache-only collections add a new memcache key for managing batch data, we need to ensure it's included in the enumeration of all keys when clearing memcache data for a user.
@Natim r?

Include batch-related memcache keys when clearing memcache data.

---

Makefile
loadtest/stress.py
syncstorage/storage/__init__.py
syncstorage/storage/memcached.py
syncstorage/storage/sql/__init__.py
syncstorage/storage/sql/queries_generic.py
syncstorage/storage/sql/queries_mysql.py
syncstorage/storage/sql/queries_postgres.py
syncstorage/storage/sql/queries_sqlite.py
syncstorage/tests/test_scripts.py
syncstorage/tests/test_wsgiapp.py
syncstorage/tests/tests-hostname.ini
syncstorage/views/__init__.py

This is, I hope, my last suite of changes against the batch-uploads branch.  It addresses a bunch of smaller nits I had in my initial review, about which I'll leave comments throughout.  @Natim r?

Address miscellaneous review nits for batch-uploads work.

---

syncstorage/storage/memcached.py
syncstorage/tests/functional/test_storage.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1342679 for reference.
There's a bug in the memcache storage layer where, if you update some existing BSOs but don't add any new ones, then the cached collection data is not updated with the new "modified" timestamp.  Anyone that looks at this cached data to determine the modified time of the collection, will think it's unmodified when it actually is.
AFAICT this bug has been here for years, but we haven't noticed it because there's an additional layer of caching that contains the timestamps for all the collections.  That layer *was* getting updated correctly, so there was never much opportunity to observe the incorrect timestamp:
1. key `<userid>:metadata` contains the last-modified time for all collections, and was being updated correctly …

Bug 1342679 - Properly track timestamps of updated items in memcached.

---

syncstorage/storage/sql/__init__.py
syncstorage/storage/sql/queries_generic.py
syncstorage/tests/functional/test_storage.py

WIP, for now this is just a failing test...

Prevent data corruption caused by batch id re-use.

---

syncstorage/storage/sql/__init__.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1364005

Bug 1364005 - Reserve new standard collection ids for formautofill data.

---

.pyup.yml

Add pyup configuration.

---

syncstorage/tests/functional/test_storage.py

Fix functional tests to run on python2.6

---

.travis.yml
syncstorage/scripts/purgettl.py
syncstorage/storage/sql/__init__.py
syncstorage/storage/sql/dbconnect.py
syncstorage/storage/sql/queries_mysql.py
syncstorage/storage/sql/queries_postgres.py
syncstorage/tests/functional/test_old_storage.py
syncstorage/tests/tests-filedb.ini

Bug 1388963 - Run `OPTIMIZE TABLE` after purging items

---

syncstorage/storage/sql/__init__.py

This will help ensure that the optimization actually gets run.
Without it, a highly-garbage-filled index could cause the purge
job to take a long time and never get around to actually running
the optimize.

Run `OPTIMIZE TABLE` before a purge, as well as after.

---

.travis.yml
Makefile
requirements.txt

Relates to https://bugzilla.mozilla.org/show_bug.cgi?id=1384283

Update some dependencies.

---

example.ini
syncstorage/storage/sql/__init__.py
syncstorage/storage/sql/dbconnect.py
syncstorage/storage/sql/queries_generic.py
syncstorage/tests/tests.ini

@autrilla this builds on your work from #86, but trying to simplify the way the config flag is passed down to the query.  I also renamed the config flag to describe the effect it will have, rather than the implementation detail.  Thoughts?

Bug 1464008 explicitly order by id config flag - rfk edits

---

docker-entrypoint.sh

Needed for bug [1520091](https://bugzilla.mozilla.org/show_bug.cgi?id=1520091).

Makes gunicorn --worker-class configurable.

---

syncstorage/tests/test_wsgiapp.py
syncstorage/views/__init__.py

Fixes #101; @pjenvey r?
Code lifted directly from the exiting route in tokenserver.

chore: Add /__lbheartbeat__ route

---

syncstorage/storage/spanner.py

for test_bad_cache issue seen in bug 1520091

fix: convert another IN operator usage to multiple bind params

---

syncstorage/storage/spanner.py

and w/ a more reasonable default than BurstyPool's 10
Closes #110

feat: support the pool_size argument

---

syncstorage/storage/spanner.py

via: _force_bsolm_index = false

feat: allow disabling the BsoLastModified index

---

syncstorage/storage/sql/queries_spanner.py

this doesn't seem to affect FIND_ITEM's query plan but including it
just in case (spanner's best practices suggests including it)

feat: force specify the higher bound for basic modified ranges

---

requirements.txt

per CVE-2019-11324 affecting < 1.24.2

chore: update urllib

---

syncstorage/tests/functional/test_storage.py

feat: improve spanner backend compatibility

---

CHANGELOG.md
setup.py

Now with lemony-fresh changelogs

chore: release/1.7.0

---

syncstorage/storage/sql/dbconnect.py
syncstorage/storage/sql/queries_generic.py
syncstorage/tests/test_sql.py
syncstorage/tests/test_wsgiapp.py

Issue syncstorage-rs/#428
Closes #143

bug: Convert the migration state to a SmallInt

---

README.md
docs/RELEASE.md

* add rfk's additional steps
* fix formatting
* link from README

doc: Fixup release docs
